<?php

########################################################################
# Extension Manager/Repository config file for ext: "bweb_vh"
#
# Auto generated by Extension Builder 2012-10-19
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bildungsweb ViewHelper',
	'description' => 'Alle Viewhelper für Bildungsweb Backend und Fronten',
	'category' => 'Frontend',
	'author' => 'Andreas Freund, Christian Hansen, Inga Pohl, Kjell Weibrecht',
	'author_email' => 'developer@bildungsweb.net',
	'author_company' => 'Bildungsweb Media GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stabil',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '0',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>